"""add kind to categories

Revision ID: 6549657f85c9
Revises: a5537f54ab55
Create Date: 2026-05-11 14:19:16.397508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6549657f85c9'
down_revision: Union[str, Sequence[str], None] = 'a5537f54ab55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('kind', sa.Enum('income', 'expense', name='category_kind', native_enum=False), server_default='expense', nullable=False))
    op.create_index(op.f('ix_categories_kind'), 'categories', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_kind'), table_name='categories')
    op.drop_column('categories', 'kind')
    # ### end Alembic commands ###
