"""create accounts table

Revision ID: 9cb96c11c799
Revises: f26b7fd0df51
Create Date: 2026-05-09 21:05:22.740589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb96c11c799'
down_revision: Union[str, Sequence[str], None] = 'f26b7fd0df51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('currency_code', sa.String(length=3), server_default='RUB', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_accounts_owner_name')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
