"""create exchange_rates table

Revision ID: a5537f54ab55
Revises: 8a7b3c2d1e4f
Create Date: 2026-05-11 12:51:32.400223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5537f54ab55'
down_revision: Union[str, Sequence[str], None] = '8a7b3c2d1e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_code', sa.String(length=3), nullable=False),
    sa.Column('num_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('vunit_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('char_code', 'rate_date', name='uq_exchange_rates_code_date')
    )
    op.create_index(op.f('ix_exchange_rates_char_code'), 'exchange_rates', ['char_code'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_date'), 'exchange_rates', ['rate_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_rate_date'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_char_code'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
