"""add kind and note to accounts

Revision ID: b2b7542ac735
Revises: 6549657f85c9
Create Date: 2026-05-11 15:55:38.941740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b7542ac735'
down_revision: Union[str, Sequence[str], None] = '6549657f85c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('kind', sa.Enum('card', 'cash', 'savings', 'credit', 'e_wallet', 'other', name='account_kind', native_enum=False), server_default='other', nullable=False))
    op.add_column('accounts', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'note')
    op.drop_column('accounts', 'kind')
    # ### end Alembic commands ###
